[project]
name = "resrm"
version = "0.4.1"
description = "drop-in replacement for rm with undo/restore built-in."
authors = [{ name = "Marco D'Aleo", email = "marco@marcodaleo.com" }]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "argcomplete>=2",
]

[project.urls]
Homepage = "https://git.sysmd.uk/guardutils/resrm"
Repository = "https://git.sysmd.uk/guardutils/resrm"

[project.scripts]
resrm = "resrm.cli:main"

[tool.poetry]
packages = [{include = "resrm", from = "src"}]

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
